// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Task": Application User Types
//
// Command:
// $ goagen
// --design=github.com/BcRikko/learning-goa/design
// --out=$(GOPATH)/src/github.com/BcRikko/learning-goa
// --version=v1.3.1

package app
